import * as fs from 'node:fs';
import * as path from 'node:path';
import { generateApi as _generateApi } from 'swagger-typescript-api';

const genApiOutput = path.resolve(process.cwd(), '../frontend/src/api/api.ts');

function trimChars(str: string, chars: string): string {
  return str.replace(new RegExp(`^[${chars}]+|[${chars}]+$`, 'g'), '');
}

async function generateApi(swaggerJSONApi: string): Promise<void> {
  const routeNameUrlMap = {};
  await _generateApi({
    silent: true,
    url: swaggerJSONApi,
    httpClientType: 'axios',
    sortRoutes: true,
    sortTypes: true,
    hooks: {
      onCreateRoute: (route) => {
        const routeKey // 驼峰转为大写常量
          = trimChars(route.routeName.usage.replace(/([A-Z])/g, '_$1').toUpperCase(), '_').replace(
            // 去除多余的_
            /_+/g,
            '_'
          );
        routeNameUrlMap[routeKey] = [route.raw.summary, route.raw.route];
        return route;
      },
      onFormatRouteName(routeInfo, _templateRouteName) {
        let routeName: string;
        const crud = ['updateOneBase', 'getManyBase', 'getOneBase', 'deleteOneBase', 'createOneBase'];
        const replaced = ['updateOne', 'getMany', 'getOne', 'deleteOne', 'createOne'];
        const index = crud.findIndex((x) => routeInfo.operationId.includes(x));
        if (index > -1) {
          const match = routeInfo.operationId.match(/Base(.*?)Controller/)!;
          routeName = `${match[1]}_${replaced[index]}`;
        } else {
          routeName = routeInfo.operationId.replace('Controller', '');
        }
        return routeName.replace(
          // 把_后面的单词转换为大写
          /_(\w)/g,
          (_, x: string) => `_${x.toUpperCase()}`
        );
      },
    },
  }).then(({ files }) => {
    const fileContent = files[0].fileContent;
    const code = `/* eslint-disable */
//@ts-ignore
//@ts-nocheck
/**
 * This file was auto-generated by swagger-typescript-api package.
 * Do not make modifications in this file.
 */
${fileContent}

export const route = {${Object.keys(routeNameUrlMap)
  .map((x) => `\n  /** ${routeNameUrlMap[x][0]} **/\n  ${x}: '${routeNameUrlMap[x][1]}'`)
  .join(',')}\n};`;
    if (fs.existsSync(genApiOutput) && fs.readFileSync(genApiOutput, 'utf-8') == code) {
      return;
    }
    fs.writeFileSync(genApiOutput, code);
  });
}

void (async () => {
  const swaggerJSONApi = process.argv[2];
  await generateApi(swaggerJSONApi);
})();
