/* eslint-disable */
//@ts-ignore
//@ts-nocheck
/**
 * This file was auto-generated by swagger-typescript-api package.
 * Do not make modifications in this file.
 */
export interface CommonResponseDto {
  /** 错误码 */
  ec: number;
  /** 错误信息 */
  em?: string;
}

export interface DeleteMemberRequestDto {
  /** 群号 */
  gc: number;
  /** p_skey */
  p_skey: string;
  /** p_uin */
  p_uin: string;
  /** skey */
  skey: string;
  /** uin */
  uin: string;
  /** 目标用户QQ号 */
  ul: number;
}

export interface GroupInfoDto {
  /** 群号 */
  gc: number;
  /** 群名称 */
  gn: string;
  /** 角色 */
  role: "creator" | "manager" | "member";
  /** 角色名称: 群主/管理员/群员 */
  roleName: string;
}

export interface GroupListRequestDto {
  /** p_skey */
  p_skey: string;
  /** p_uin */
  p_uin: string;
  /** skey */
  skey: string;
  /** uin */
  uin: string;
}

export interface GroupListResponseDto {
  /** 错误码 */
  errcode: number;
  /** 群列表 */
  list: GroupInfoDto[];
}

export interface GroupMemberDto {
  /** 群名片 */
  card: string;
  /** 标志 */
  flag: number;
  /** 性别: 0=男, 1=女, 其他未知 */
  g: number;
  /** 加群时间 */
  join_time: number;
  /** 最后发言时间 */
  last_speak_time: number;
  /** 等级信息 */
  lv: MemberLevelDto;
  /** 昵称 */
  nick: string;
  /** Q龄 */
  qage: number;
  /** 是否有权限踢出 */
  rm: number;
  /** 角色:0=群主,1=管理员,2=成员 */
  role: 0 | 1 | 2;
  /** 标签 */
  tags: string;
  /** QQ号 */
  uin: number;
}

export interface GroupMembersRequestDto {
  /** 结束位置 */
  end: number;
  /** 群号 */
  gc: number;
  /** p_skey */
  p_skey: string;
  /** p_uin */
  p_uin: string;
  /** skey */
  skey: string;
  /** 起始位置 */
  st: number;
  /** uin */
  uin: string;
}

export interface GroupMembersResponseDto {
  /** 管理员数量 */
  adm_num: number;
  /** 总数 */
  count: number;
  /** 错误码 */
  ec: number;
  /** 错误信息 */
  em: string;
  /** 错误码 */
  errcode: number;
  /** 等级名称映射 */
  levelname: object;
  /** 最大人数 */
  max_count: number;
  /** 成员列表 */
  mems: GroupMemberDto[];
  /** 搜索结果数 */
  search_count: number;
  /** 服务器时间 */
  svr_time: number;
}

export interface IQQLoginCookies {
  pt2gguin?: string;
  pt4_token?: string;
  RK?: string;
  p_skey?: string;
  p_uin?: string;
  pt_recent_uins?: string;
  ptcz?: string;
  ptnick_?: string;
  skey?: string;
  superkey?: string;
  supertoken?: string;
  superuin?: string;
  uin?: string;
}

export interface LoginGetResultReqDto {
  qrsig: string;
}

export interface LoginResultResponseDto {
  code: number;
  cookies?: IQQLoginCookies;
  msg: string;
  uin?: string;
}

export interface MemberLevelDto {
  /** 等级 */
  level: number;
  /** 积分 */
  point: number;
}

export interface QrcodeResponseDto {
  image: string;
  qrsig: string;
}

export interface SetGroupCardRequestDto {
  /** 群号 */
  gc: number;
  /** 新名片 */
  name: string;
  /** p_skey */
  p_skey: string;
  /** p_uin */
  p_uin: string;
  /** skey */
  skey: string;
  /** 目标用户QQ号 */
  u: number;
  /** uin */
  uin: string;
}

import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse,
  HeadersDefaults,
  ResponseType,
} from "axios";
import axios from "axios";

export type QueryParamsType = Record<string | number, any>;

export interface FullRequestParams
  extends Omit<AxiosRequestConfig, "data" | "params" | "url" | "responseType"> {
  /** set parameter to `true` for call `securityWorker` for this request */
  secure?: boolean;
  /** request path */
  path: string;
  /** content type of request body */
  type?: ContentType;
  /** query params */
  query?: QueryParamsType;
  /** format of response (i.e. response.json() -> format: "json") */
  format?: ResponseType;
  /** request body */
  body?: unknown;
}

export type RequestParams = Omit<
  FullRequestParams,
  "body" | "method" | "query" | "path"
>;

export interface ApiConfig<SecurityDataType = unknown>
  extends Omit<AxiosRequestConfig, "data" | "cancelToken"> {
  securityWorker?: (
    securityData: SecurityDataType | null,
  ) => Promise<AxiosRequestConfig | void> | AxiosRequestConfig | void;
  secure?: boolean;
  format?: ResponseType;
}

export enum ContentType {
  Json = "application/json",
  JsonApi = "application/vnd.api+json",
  FormData = "multipart/form-data",
  UrlEncoded = "application/x-www-form-urlencoded",
  Text = "text/plain",
}

export class HttpClient<SecurityDataType = unknown> {
  public instance: AxiosInstance;
  private securityData: SecurityDataType | null = null;
  private securityWorker?: ApiConfig<SecurityDataType>["securityWorker"];
  private secure?: boolean;
  private format?: ResponseType;

  constructor({
    securityWorker,
    secure,
    format,
    ...axiosConfig
  }: ApiConfig<SecurityDataType> = {}) {
    this.instance = axios.create({
      ...axiosConfig,
      baseURL: axiosConfig.baseURL || "",
    });
    this.secure = secure;
    this.format = format;
    this.securityWorker = securityWorker;
  }

  public setSecurityData = (data: SecurityDataType | null) => {
    this.securityData = data;
  };

  protected mergeRequestParams(
    params1: AxiosRequestConfig,
    params2?: AxiosRequestConfig,
  ): AxiosRequestConfig {
    const method = params1.method || (params2 && params2.method);

    return {
      ...this.instance.defaults,
      ...params1,
      ...(params2 || {}),
      headers: {
        ...((method &&
          this.instance.defaults.headers[
            method.toLowerCase() as keyof HeadersDefaults
          ]) ||
          {}),
        ...(params1.headers || {}),
        ...((params2 && params2.headers) || {}),
      },
    };
  }

  protected stringifyFormItem(formItem: unknown) {
    if (typeof formItem === "object" && formItem !== null) {
      return JSON.stringify(formItem);
    } else {
      return `${formItem}`;
    }
  }

  protected createFormData(input: Record<string, unknown>): FormData {
    if (input instanceof FormData) {
      return input;
    }
    return Object.keys(input || {}).reduce((formData, key) => {
      const property = input[key];
      const propertyContent: any[] =
        property instanceof Array ? property : [property];

      for (const formItem of propertyContent) {
        const isFileType = formItem instanceof Blob || formItem instanceof File;
        formData.append(
          key,
          isFileType ? formItem : this.stringifyFormItem(formItem),
        );
      }

      return formData;
    }, new FormData());
  }

  public request = async <T = any, _E = any>({
    secure,
    path,
    type,
    query,
    format,
    body,
    ...params
  }: FullRequestParams): Promise<AxiosResponse<T>> => {
    const secureParams =
      ((typeof secure === "boolean" ? secure : this.secure) &&
        this.securityWorker &&
        (await this.securityWorker(this.securityData))) ||
      {};
    const requestParams = this.mergeRequestParams(params, secureParams);
    const responseFormat = format || this.format || undefined;

    if (
      type === ContentType.FormData &&
      body &&
      body !== null &&
      typeof body === "object"
    ) {
      body = this.createFormData(body as Record<string, unknown>);
    }

    if (
      type === ContentType.Text &&
      body &&
      body !== null &&
      typeof body !== "string"
    ) {
      body = JSON.stringify(body);
    }

    return this.instance.request({
      ...requestParams,
      headers: {
        ...(requestParams.headers || {}),
        ...(type ? { "Content-Type": type } : {}),
      },
      params: query,
      responseType: responseFormat,
      data: body,
      url: path,
    });
  };
}

/**
 * @title QQ GroupKit
 * @version 2.0.0
 * @contact
 */
export class Api<
  SecurityDataType extends unknown,
> extends HttpClient<SecurityDataType> {
  api = {
    /**
     * No description
     *
     * @tags App
     * @name AppDeleteMember
     * @summary 删除群成员
     * @request POST:/api/delete-member
     */
    App_DeleteMember: (
      data: DeleteMemberRequestDto,
      params: RequestParams = {},
    ) =>
      this.request<CommonResponseDto, any>({
        path: `/api/delete-member`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @tags App
     * @name AppGetGroupList
     * @summary 获取群列表
     * @request POST:/api/group-list
     */
    App_GetGroupList: (data: GroupListRequestDto, params: RequestParams = {}) =>
      this.request<GroupListResponseDto, any>({
        path: `/api/group-list`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @tags App
     * @name AppGetGroupMembers
     * @summary 获取群成员列表
     * @request POST:/api/group-members
     */
    App_GetGroupMembers: (
      data: GroupMembersRequestDto,
      params: RequestParams = {},
    ) =>
      this.request<GroupMembersResponseDto, any>({
        path: `/api/group-members`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @tags App
     * @name AppGetQrcode
     * @summary 获取登录二维码
     * @request POST:/api/get-qrcode
     */
    App_GetQrcode: (params: RequestParams = {}) =>
      this.request<QrcodeResponseDto, any>({
        path: `/api/get-qrcode`,
        method: "POST",
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @tags App
     * @name AppGetResult
     * @summary 获取登录结果
     * @request POST:/api/get-result
     */
    App_GetResult: (data: LoginGetResultReqDto, params: RequestParams = {}) =>
      this.request<LoginResultResponseDto, any>({
        path: `/api/get-result`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @tags App
     * @name AppSetGroupCard
     * @summary 修改群名片
     * @request POST:/api/set-group-card
     */
    App_SetGroupCard: (
      data: SetGroupCardRequestDto,
      params: RequestParams = {},
    ) =>
      this.request<CommonResponseDto, any>({
        path: `/api/set-group-card`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),
  };
}


export const route = {
  /** 获取登录二维码 **/
  APP_GET_QRCODE: '/api/get-qrcode',
  /** 获取登录结果 **/
  APP_GET_RESULT: '/api/get-result',
  /** 获取群列表 **/
  APP_GET_GROUP_LIST: '/api/group-list',
  /** 获取群成员列表 **/
  APP_GET_GROUP_MEMBERS: '/api/group-members',
  /** 修改群名片 **/
  APP_SET_GROUP_CARD: '/api/set-group-card',
  /** 删除群成员 **/
  APP_DELETE_MEMBER: '/api/delete-member'
};